# -----------------------------------------------------------------------------
# Auto-generated by STM32CubeIDE for Visual Studio Code Extension
# Modified: added HAL + FreeRTOS sources
# -----------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.20)

# Core MCU flags, CPU, instruction set and FPU setup
set(cpu_PARAMS ${CPU_FLAGS} ${cpu_PARAMS})

# Linker script
set(linker_script_SRC ${linker_script_SRC}
	${CMAKE_CURRENT_SOURCE_DIR}/stm32f103x8_flash.ld
)

# Sources
set(sources_SRCS ${sources_SRCS}
	${CMAKE_CURRENT_SOURCE_DIR}/Src/syscall.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/sysmem.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/startup_stm32f103xx.S
	${CMAKE_CURRENT_SOURCE_DIR}/Src/system_stm32f1xx.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32f1xx_hal_msp.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32f1xx_it.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32f1xx_hal_timebase_tim.c
)

# HAL Driver sources
file(GLOB HAL_SRCS
	${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/*.c
)
set(sources_SRCS ${sources_SRCS} ${HAL_SRCS})

# FreeRTOS kernel sources
set(sources_SRCS ${sources_SRCS}
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/tasks.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/queue.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/list.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/timers.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/event_groups.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/stream_buffer.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/croutine.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c
	${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS/Source/portable/MemMang/heap_4.c
)

# Include directories
set(include_c_DIRS ${include_c_DIRS}
)
set(include_cxx_DIRS ${include_cxx_DIRS}
)
set(include_asm_DIRS ${include_asm_DIRS}
)

# Symbols definition
set(symbols_c_SYMB ${symbols_c_SYMB}
	USE_HAL_DRIVER
	STM32F103xB
)
set(symbols_cxx_SYMB ${symbols_cxx_SYMB}
)
set(symbols_asm_SYMB ${symbols_asm_SYMB}
)

# Link directories
set(link_DIRS ${link_DIRS}
)

# Link libraries
set(link_LIBS ${link_LIBS}
)

# Compiler options
set(compiler_OPTS ${compiler_OPTS} ${SECURE_FLAGS})

# Linker options
set(linker_OPTS ${linker_OPTS})